### ISSUE TITLE
German Language Support

### ISSUE THREAD

**Issue by rs-11** [KSU-Linux/dokuwiki-template-bulma#1]
Hello
The template looks great, but german language support is poorly, because äöü are not rendered correctly, not it content text and not in the settings!

**Comment by miralgj** [comment]
I think this is due to the in-place DOM modifications the theme does before showing content; it is not encoding it as UTF-8 properly.

**Comment by miralgj** [comment]
Check if newest commit to main resolves your issue.

**Comment by miralgj** [comment]
Marking this as closed as the newest commits appear to have fixed the issue.
