### ISSUE TITLE
Dokuwiki says that the extension is updatable

### ISSUE THREAD

**Issue by Moini** [KSU-Linux/dokuwiki-template-bulma#2]
... but it's only that the date in https://github.com/KSU-Linux/dokuwiki-template-bulma/blob/main/template.info.txt has not been updated.

![grafik](https://user-images.githubusercontent.com/3240233/213822798-6b3256d6-53e1-48fe-ae48-2d68e705a52f.png)

Could you please make a new release where the date has been updated?

**Comment by miralgj** [comment]
Didn't realize the last updated date in dokuwiki.org/template:bulma had any significance with regards to that. I changed the date in `template.info.txt` to match.

**Comment by Moini** [comment]
Thank you!!! :D
