### ISSUE TITLE
Display issues on admin pages

### ISSUE THREAD

**Issue by bitmind** [KSU-Linux/dokuwiki-template-bulma#3]
This template is awesome, however there is an issue with Admin sections. Some fields are misplaced and overlapping. Existintg ACLs are not properly rendered.
<img width="927" alt="screen7225" src="https://github.com/KSU-Linux/dokuwiki-template-bulma/assets/9748401/f94875c2-c6e8-4f71-a5e3-5df08550f8b6">

**Comment by miralgj** [comment]
Fixed in commit c60e8d6
